### ISSUE TITLE
create: true throw me an error

### ISSUE THREAD

**Issue by scenaristeur** [fluree/fluree-client#4]
using server `docker run -p 58090:8090 -v `pwd`/data:/opt/fluree-server/data fluree/server:df51739cf942d67f17331963a895fb097cbced5e` and not the last because of https://github.com/fluree/server/issues/54

and flurry-client 
```
  async createThing(context, thing) {
    thing.created = Date.now()

    // https://github.com/fluree/fluree-client?tab=readme-ov-file#client-config
    const client = await new FlureeClient({
      host: 'localhost',
      port: 58090,
      ledger: 'cryptids',
      create: true,
    }).connect();

 console.log(client)
const transactionInstance = client.transact({
  //insert: { '@id': 'freddy', name: 'Freddy' },
  insert: thing
});
```
throw me an error

![image](https://github.com/fluree/fluree-client/assets/4020744/1b12853e-c541-4074-8bfd-ced6f49da810)

```
2024-04-21T11:19:55.419953110Z :post "/fluree/create" => Ledger cryptids already exists
clojure.lang.ExceptionInfo: Ledger cryptids already exists {:response {:status 409, :body {:error "Ledger cryptids already exists"}}}
	at fluree.server.handlers.create$throw_ledger_exists.invokeStatic(create.clj:69)
	at fluree.server.handlers.create$throw_ledger_exists.invoke(create.clj:66)
	at fluree.server.handlers.create$default.invokeStatic(create.clj:84)
	at fluree.server.handlers.create$default.invoke(create.clj:73)
	at clojure.lang.Var.invoke(Var.java:384)

```
but in the doc, it says "    create, // [boolean] If true, the ledger will be created if it does not exist"  https://github.com/fluree/fluree-client?tab=readme-ov-file#client-config . I though the ledger would be created if not exist, but would by pass creation if it exists

**Comment by Admin661** [comment]
Hi, is the issue resolved yet? You'll have to rectify with the ledger loptimal weblink and try it again.
